name: CI

on:
  create:
    tags:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Native Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          # llvm 9 build is broken on windows for now. Re-enable this when it is fixed:
          # - windows-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Install ninja (Windows)
        run: choco install ninja
        if: matrix.os == 'windows-latest'
      - name: Install ninja (macOS)
        run: brew install ninja
        if: matrix.os == 'macos-latest'
      - name: Install ninja (Linux)
        run: sudo apt install ninja-build
        if: matrix.os == 'ubuntu-latest'
      - name: Build
        run: sudo make -j4 package
      - name: Run the testsuite
        run: make check
        if: matrix.os == 'ubuntu-latest'
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          # Upload the dist folder. Give it a name according to the OS it was built for.
          name: ${{ format( 'dist-{0}.tgz', matrix.os) }}
          path: dist

  dockerbuild:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Run docker_build script
        run: ./docker_build.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          # Upload the dist folder. Give it a name according to the OS it was built for.
          name: dist-docker.tgz
          path: dist
